version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-mysql-app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
#    command:  tail -f /dev/null

volumes: 
  db-config:
  db-data: